spring:
  application:
    name: Product Service
  datasource:
    url: jdbc:h2:mem:examenT2DB
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
        
