spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_students_ms?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQLDialect5
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 744171173544-6r0e9tff48g4h4ne80h0jehd0eqe9q58.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
